version: 1.0.{build}

image: Visual Studio 2022

environment:
  NODE_ENV: 'production'

install:
  - ps: Install-Product node 20
  - npm cache clean --force
  - npm ci
  - npm install webpack webpack-cli --save-dev
  - ps: if (Test-Path node_modules\.bin) { dir node_modules\.bin } else { Write-Host ".bin folder not found" }
  - ps: echo $env:PATH
  - ps: node -v
  - ps: npm -v
  - ps: npx --version
  - ps: npx webpack --version

build_script:
  - npm run build

deploy_script:
  - ps: |
      git config --global user.email "evgenia.maksimovna00@gmail.com"
      git config --global user.name "Евгения"
      npx gh-pages -d dist -r https://%GITHUB_TOKEN%@github.com/FilSado/collapsible-widget.git

artifacts:
  - path: dist
    name: dist
