version: 1.0.{build}

image: Visual Studio 2022

build_script:
  - cmd: npm install
  - cmd: npm run build

deploy_script:
  - ps: |
      git config --global user.email "evgenia.maksimovna00@gmail.com"
      git config --global user.name "Евгения"
      git clone https://github.com/FilSado/collapsible-widget.git deploy_repo
      cd deploy_repo
      git checkout gh-pages || git checkout --orphan gh-pages
      Remove-Item -Recurse -Force *  # Очистить ветку gh-pages
      Copy-Item -Recurse -Force ../dist/* .
      git add .
      git commit -m "Deploy to GitHub Pages - build $(appveyor_build_version)"
      git push origin gh-pages --force

